use_frameworks!

target 'EGPageViewController_Example' do
  pod 'EGPageViewController', :path => '../'

  target 'EGPageViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'SnapKit'
  end
end
